name: "Pull Request Labeler"
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
